version: 2
jobs:
  build:
    docker:
      - image : circleci/node:8.11.1-stretch
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback 
            - v1-dependencies-
      - run: npm install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
  test:
    docker:
      - image : circleci/node:8.11.1-stretch
    working_directory : ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback 
            - v1-dependencies-
      - run: npm install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - run: npm run test
  ship:
    docker:
        - image: circleci/node:8.11.1-stretch
    steps:
      - checkout
      - restore_cache :
          keys:
            - v1-dependencies-{{checksum "package.json"}}
            - v1-dependencies-
      - setup_remote_docker
      - run: docker login $URL_DOCKER -u $USER_DOCKER  -p $PASSWORD_DOCKER
      - run:
          name: "Build Docker"
          command:  |
              cp Dockerfile.production  Dockerfile
              docker build -t registry.gitlab.com/tawai.global/nodedemocircle-ci:latest .
              docker build -t registry.gitlab.com/tawai.global/nodedemocircle-ci:${VER}
              docker push registry.gitlab.com/tawai.global/nodedemocircle-ci:latest .
              docker push registry.gitlab.com/tawai.global/nodedemocircle-ci:${VER}
  deploy:
    docker:
      - image: circleci/node:8.11.1-stretch
    steps :
      - checkout
      - run :
          name: "Deploy"
          command: |
            docker run --rm -it \
              -e CATTLE_ACCESS_KEY="$CATTLE_ACCESS_KEY" \
              -e CATTLE_SECRET_KEY="$CATTLE_SECRET_KEY" \
              -e CATTLE_URL="$CATTLE_URL" \
              etlweather/gaucho upgrade $SEVICE_ID \
              --imageUuid 'docker:registry.gitlab.com/tawai.global/nodedemocircle-ci:latest' \
              --batch_size 3 --start_first \
              --auto_complete --timeout 600
      - run: echo Done

workflows:
  version: 2
  build_test_ship_deploy:
    jobs:
      - build
      - test:
          requires:
            - build
      - ship:
          requires:
            - build
            - test
      - deploy:
          requires:
            - ship


